"""
AegisFlow - Download Service
Phase 2: Generate PDF, Markdown, ZIP downloads
"""
import os
import io
import zipfile
import json
from datetime import datetime
from typing import Dict, Any, List, Optional


LANGUAGE_EXTENSIONS = {
    "python": ".py", "javascript": ".js", "typescript": ".ts",
    "java": ".java", "go": ".go", "ruby": ".rb", "php": ".php",
    "c": ".c", "cpp": ".cpp", "swift": ".swift"
}


def generate_markdown_report(scan_data: Dict) -> bytes:
    """Generate a Markdown security report"""
    vulns = scan_data.get("vulnerabilities", [])
    filename = scan_data.get("filename", "unknown")
    language = scan_data.get("language", "unknown")
    risk = scan_data.get("risk_level", "UNKNOWN")
    timestamp = scan_data.get("timestamp", datetime.utcnow().isoformat())
    fixed_code = scan_data.get("fixed_code", "")
    original_code = scan_data.get("original_code", "")

    critical = [v for v in vulns if v.get("severity") == "CRITICAL"]
    high = [v for v in vulns if v.get("severity") == "HIGH"]
    medium = [v for v in vulns if v.get("severity") == "MEDIUM"]
    low = [v for v in vulns if v.get("severity") == "LOW"]

    md = f"""# 🛡️ AegisFlow Security Report

**File:** `{filename}`  
**Language:** {language.title()}  
**Risk Level:** {risk}  
**Scan Date:** {timestamp[:19].replace("T", " ")}  
**Total Vulnerabilities:** {len(vulns)}

---

## 📊 Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | {len(critical)} |
| 🟠 High | {len(high)} |
| 🟡 Medium | {len(medium)} |
| 🟢 Low | {len(low)} |

---

## 🔍 Vulnerabilities Found

"""
    for i, v in enumerate(vulns, 1):
        severity_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(v.get("severity"), "⚪")
        md += f"""### {i}. {severity_emoji} {v.get('type', 'Unknown')}

- **Severity:** {v.get('severity', 'UNKNOWN')}
- **Line:** {v.get('line', 'N/A')}
- **CWE:** {v.get('cwe_id', 'N/A')}
- **OWASP:** {v.get('owasp_id', 'N/A')}
- **Confidence:** {round(v.get('confidence', 0) * 100)}%
- **Description:** {v.get('description', 'No description')}

"""
        if v.get("code_snippet"):
            md += f"```{language}\n{v['code_snippet']}\n```\n\n"

    if original_code:
        md += f"""---

## 📄 Original Code

```{language}
{original_code}
```

"""

    if fixed_code:
        md += f"""---

## ✅ Fixed Code

```{language}
{fixed_code}
```

"""

    md += f"""---

## 🏢 About AegisFlow

AegisFlow is an AI-powered DevSecOps platform that automatically detects and fixes security vulnerabilities.

*Report generated by AegisFlow v2.0 — {datetime.utcnow().strftime('%Y-%m-%d')}*
"""
    return md.encode("utf-8")


def generate_pdf_report(scan_data: Dict) -> bytes:
    """Generate PDF using reportlab"""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor, black, white
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.units import cm
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                 rightMargin=2*cm, leftMargin=2*cm,
                                 topMargin=2*cm, bottomMargin=2*cm)

        styles = getSampleStyleSheet()
        teal = HexColor("#06b6d4")
        coral = HexColor("#f97316")
        dark = HexColor("#0f172a")
        danger = HexColor("#ef4444")
        warn = HexColor("#f59e0b")
        success = HexColor("#10b981")
        gray = HexColor("#64748b")

        title_style = ParagraphStyle("Title", parent=styles["Title"],
                                      textColor=teal, fontSize=22, spaceAfter=6)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                                   textColor=dark, fontSize=14, spaceAfter=4)
        body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                     fontSize=10, spaceAfter=3, textColor=dark)

        vulns = scan_data.get("vulnerabilities", [])
        filename = scan_data.get("filename", "unknown")
        language = scan_data.get("language", "unknown")
        risk = scan_data.get("risk_level", "UNKNOWN")
        timestamp = scan_data.get("timestamp", datetime.utcnow().isoformat())[:19].replace("T", " ")

        story = []

        # Header
        story.append(Paragraph("🛡️ AegisFlow Security Report", title_style))
        story.append(Spacer(1, 0.3*cm))
        story.append(HRFlowable(width="100%", thickness=2, color=teal))
        story.append(Spacer(1, 0.3*cm))

        # Metadata table
        meta_data = [
            ["File", filename, "Language", language.title()],
            ["Risk Level", risk, "Scan Date", timestamp],
            ["Total Vulnerabilities", str(len(vulns)), "Scan ID", scan_data.get("scan_id", "N/A")[:16]],
        ]
        meta_table = Table(meta_data, colWidths=[3.5*cm, 5.5*cm, 3.5*cm, 5.5*cm])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), HexColor("#f8fafc")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), teal),
            ("TEXTCOLOR", (2, 0), (2, -1), teal),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.5*cm))

        # Summary
        story.append(Paragraph("📊 Vulnerability Summary", h2_style))
        critical = len([v for v in vulns if v.get("severity") == "CRITICAL"])
        high = len([v for v in vulns if v.get("severity") == "HIGH"])
        medium = len([v for v in vulns if v.get("severity") == "MEDIUM"])
        low = len([v for v in vulns if v.get("severity") == "LOW"])

        sum_data = [
            ["Severity", "Count", "Action Required"],
            ["🔴 CRITICAL", str(critical), "Immediate fix required"],
            ["🟠 HIGH", str(high), "Fix before deployment"],
            ["🟡 MEDIUM", str(medium), "Fix in next sprint"],
            ["🟢 LOW", str(low), "Fix when convenient"],
        ]
        sum_table = Table(sum_data, colWidths=[5*cm, 3*cm, 10*cm])
        sum_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), dark),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#f8fafc")]),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ]))
        story.append(sum_table)
        story.append(Spacer(1, 0.5*cm))

        # Vulnerabilities
        if vulns:
            story.append(Paragraph("🔍 Detailed Findings", h2_style))
            for i, v in enumerate(vulns, 1):
                sev = v.get("severity", "UNKNOWN")
                sev_color = {"CRITICAL": danger, "HIGH": coral, "MEDIUM": warn, "LOW": success}.get(sev, gray)

                vuln_data = [
                    [f"{i}. {v.get('type', 'Unknown')}", f"Severity: {sev}"],
                    [f"Line: {v.get('line', 'N/A')} | CWE: {v.get('cwe_id', 'N/A')} | Confidence: {round(v.get('confidence', 0)*100)}%", ""],
                    [v.get("description", ""), ""],
                ]
                if v.get("code_snippet"):
                    vuln_data.append([f"Code: {v['code_snippet']}", ""])

                vtable = Table(vuln_data, colWidths=[14*cm, 4*cm])
                vtable.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), sev_color),
                    ("TEXTCOLOR", (0, 0), (-1, 0), white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.3, HexColor("#e2e8f0")),
                    ("BACKGROUND", (0, 1), (-1, -1), HexColor("#f8fafc")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("SPAN", (0, 1), (1, 1)),
                    ("SPAN", (0, 2), (1, 2)),
                ]))
                story.append(vtable)
                story.append(Spacer(1, 0.3*cm))

        # Footer
        story.append(Spacer(1, 0.5*cm))
        story.append(HRFlowable(width="100%", thickness=1, color=teal))
        story.append(Paragraph(
            f"<i>Generated by AegisFlow v2.0 — AI-Powered Security Platform — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC</i>",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=gray, alignment=TA_CENTER)
        ))

        doc.build(story)
        return buffer.getvalue()

    except Exception as e:
        print(f"PDF generation error: {e}")
        # Return markdown as fallback
        return generate_markdown_report(scan_data)


def generate_repo_pdf_report(scan_data: Dict) -> bytes:
    """Generate PDF for repository scan using reportlab"""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor, black, white
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.units import cm
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                 rightMargin=2*cm, leftMargin=2*cm,
                                 topMargin=2*cm, bottomMargin=2*cm)

        styles = getSampleStyleSheet()
        teal = HexColor("#06b6d4")
        coral = HexColor("#f97316")
        dark = HexColor("#0f172a")
        danger = HexColor("#ef4444")
        warn = HexColor("#f59e0b")
        success = HexColor("#10b981")
        gray = HexColor("#64748b")

        title_style = ParagraphStyle("Title", parent=styles["Title"],
                                      textColor=teal, fontSize=22, spaceAfter=6)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                                   textColor=dark, fontSize=14, spaceAfter=4)
        body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                     fontSize=10, spaceAfter=3, textColor=dark)

        repo_name = scan_data.get("repo_name", "unknown")
        branch = scan_data.get("branch", "main")
        risk = scan_data.get("overall_risk", "UNKNOWN")
        timestamp = scan_data.get("timestamp", datetime.utcnow().isoformat())[:19].replace("T", " ")
        vuln_summary = scan_data.get("vulnerability_summary", {})
        top_files = scan_data.get("top_vulnerable_files", [])

        story = []

        # Header
        story.append(Paragraph("🛡️ AegisFlow Repository Report", title_style))
        story.append(Spacer(1, 0.3*cm))
        story.append(HRFlowable(width="100%", thickness=2, color=teal))
        story.append(Spacer(1, 0.3*cm))

        # Metadata table
        meta_data = [
            ["Repository", repo_name, "Branch", branch],
            ["Overall Risk", risk, "Scan Date", timestamp],
            ["Total Files Scanned", str(scan_data.get("total_files_scanned", 0)), "Total Vulns", str(scan_data.get("total_vulnerabilities", 0))],
        ]
        meta_table = Table(meta_data, colWidths=[3.5*cm, 5.5*cm, 3.5*cm, 5.5*cm])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), HexColor("#f8fafc")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), teal),
            ("TEXTCOLOR", (2, 0), (2, -1), teal),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.5*cm))

        # Summary
        story.append(Paragraph("📊 Vulnerability Summary", h2_style))
        critical = vuln_summary.get("CRITICAL", 0)
        high = vuln_summary.get("HIGH", 0)
        medium = vuln_summary.get("MEDIUM", 0)
        low = vuln_summary.get("LOW", 0)

        sum_data = [
            ["Severity", "Count"],
            ["🔴 CRITICAL", str(critical)],
            ["🟠 HIGH", str(high)],
            ["🟡 MEDIUM", str(medium)],
            ["🟢 LOW", str(low)],
        ]
        sum_table = Table(sum_data, colWidths=[5*cm, 3*cm])
        sum_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), dark),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#f8fafc")]),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ]))
        story.append(sum_table)
        story.append(Spacer(1, 0.5*cm))

        if scan_data.get("gemini_repo_analysis"):
            story.append(Paragraph("🤖 AI Executive Summary", h2_style))
            story.append(Paragraph(scan_data["gemini_repo_analysis"].replace('\n', '<br/>'), body_style))
            story.append(Spacer(1, 0.5*cm))

        if top_files:
            story.append(Paragraph("🚨 Top Vulnerable Files", h2_style))
            tf_data = [["Filename", "Risk Level", "Vulns Found"]]
            for f in top_files:
                tf_data.append([f["filename"], f["risk_level"], str(f["total_found"])])
            
            tf_table = Table(tf_data, colWidths=[10*cm, 4*cm, 4*cm])
            tf_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), dark),
                ("TEXTCOLOR", (0, 0), (-1, 0), white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#e2e8f0")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, HexColor("#f8fafc")]),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(tf_table)
            story.append(Spacer(1, 0.3*cm))

        # Footer
        story.append(Spacer(1, 0.5*cm))
        story.append(HRFlowable(width="100%", thickness=1, color=teal))
        story.append(Paragraph(
            f"<i>Generated by AegisFlow v2.0 — AI-Powered Security Platform — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC</i>",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=gray, alignment=TA_CENTER)
        ))

        doc.build(story)
        return buffer.getvalue()

    except Exception as e:
        print(f"PDF repo generation error: {e}")
        return b"Error generating PDF report."


def generate_zip_download(scan_data: Dict, files: List[Dict]) -> bytes:
    """Generate ZIP with fixed files + report"""
    buffer = io.BytesIO()
    language = scan_data.get("language", "python")
    ext = LANGUAGE_EXTENSIONS.get(language, ".txt")

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add fixed files
        for file in files:
            fname = file.get("filename", f"fixed_file{ext}")
            content = file.get("fixed_code") or file.get("original_code", "")
            if content:
                zf.writestr(f"fixed/{fname}", content)
            orig = file.get("original_code", "")
            if orig:
                zf.writestr(f"original/{fname}", orig)

        # Add markdown report
        md = generate_markdown_report(scan_data)
        zf.writestr("report/security_report.md", md.decode("utf-8"))

        # Add JSON data
        json_data = json.dumps({
            "scan_id": scan_data.get("scan_id"),
            "filename": scan_data.get("filename"),
            "language": language,
            "risk_level": scan_data.get("risk_level"),
            "vulnerabilities": scan_data.get("vulnerabilities", []),
            "timestamp": scan_data.get("timestamp"),
        }, indent=2, default=str)
        zf.writestr("report/scan_data.json", json_data)

        # Add README
        readme = f"""# AegisFlow Security Scan Results

## Scan Summary
- **File:** {scan_data.get('filename', 'unknown')}
- **Risk Level:** {scan_data.get('risk_level', 'UNKNOWN')}
- **Vulnerabilities Found:** {len(scan_data.get('vulnerabilities', []))}

## Contents
- `fixed/` — Fixed source files
- `original/` — Original source files
- `report/security_report.md` — Full security report
- `report/scan_data.json` — Raw scan data

## How to Use
1. Review `report/security_report.md` for full analysis
2. Compare `original/` vs `fixed/` to see changes
3. Test the fixed code before deploying

*Generated by AegisFlow v2.0*
"""
        zf.writestr("README.md", readme)

    return buffer.getvalue()


def generate_repo_markdown_report(scan_data: Dict) -> bytes:
    """Generate Markdown report for repository scan"""
    repo_name = scan_data.get("repo_name", "unknown")
    branch = scan_data.get("branch", "main")
    risk = scan_data.get("overall_risk", "UNKNOWN")
    timestamp = scan_data.get("timestamp", datetime.utcnow().isoformat())[:19].replace("T", " ")
    
    md = f"""# 🛡️ AegisFlow Repository Security Report

**Repository:** `{repo_name}`  
**Branch:** `{branch}`  
**Overall Risk Level:** {risk}  
**Scan Date:** {timestamp}  
**Total Files Scanned:** {scan_data.get('total_files_scanned', 0)}  
**Total Vulnerabilities:** {scan_data.get('total_vulnerabilities', 0)}  

---

## 📊 Summary

"""
    vuln_summary = scan_data.get("vulnerability_summary", {})
    md += f"""| Severity | Count |
|----------|-------|
| 🔴 CRITICAL | {vuln_summary.get('CRITICAL', 0)} |
| 🟠 HIGH | {vuln_summary.get('HIGH', 0)} |
| 🟡 MEDIUM | {vuln_summary.get('MEDIUM', 0)} |
| 🟢 LOW | {vuln_summary.get('LOW', 0)} |

---
"""
    if scan_data.get("gemini_repo_analysis"):
        md += f"""## 🤖 AI Executive Summary\n\n{scan_data['gemini_repo_analysis']}\n\n---\n"""

    md += "## 🔍 Detailed Findings\n\n"
    for file in scan_data.get("files", []):
        if file.get("total_found", 0) > 0:
            md += f"### File: `{file['filename']}`\n"
            md += f"- **Risk Level:** {file.get('risk_level', 'UNKNOWN')}\n"
            md += f"- **Vulnerabilities Found:** {file.get('total_found', 0)}\n\n"
            for v in file.get("vulnerabilities", []):
                sev_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(v.get("severity"), "⚪")
                md += f"#### {sev_emoji} {v.get('type', 'Unknown')} ({v.get('severity')})\n"
                md += f"- **Line:** {v.get('line', 'N/A')}\n"
                md += f"- **Description:** {v.get('description', 'N/A')}\n\n"
            md += "---\n"
            
    md += f"""
*Generated by AegisFlow v2.0 — AI-Powered Security Platform*
"""
    return md.encode("utf-8")


def generate_repo_zip_download(scan_data: Dict) -> bytes:
    """Generate ZIP with fixed files + report for repository"""
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add files (preserving directory structure)
        for file in scan_data.get("files", []):
            if file.get("total_found", 0) > 0:
                fname = file.get("filename", "unknown.txt")
                
                # If there's a fix, save both original and fixed
                fixed = file.get("fixed_code")
                orig = file.get("original_code")
                
                if fixed:
                    zf.writestr(f"fixed/{fname}", fixed)
                if orig:
                    zf.writestr(f"original/{fname}", orig)

        # Add markdown report
        md = generate_repo_markdown_report(scan_data)
        zf.writestr("report/repository_report.md", md.decode("utf-8"))

        # Add JSON data (excluding full code to keep it small)
        safe_scan_data = {k: v for k, v in scan_data.items() if k != "files"}
        safe_scan_data["files"] = [{"filename": f["filename"], "vulnerabilities": f["vulnerabilities"]} for f in scan_data.get("files", []) if f.get("total_found", 0) > 0]
        
        json_data = json.dumps(safe_scan_data, indent=2, default=str)
        zf.writestr("report/scan_data.json", json_data)

        # Add README
        readme = f"""# AegisFlow Repository Scan Results

## Scan Summary
- **Repository:** {scan_data.get('repo_name', 'unknown')}
- **Risk Level:** {scan_data.get('overall_risk', 'UNKNOWN')}
- **Total Vulns:** {scan_data.get('total_vulnerabilities', 0)}

## Contents
- `fixed/` — Fixed source files with directory structure preserved
- `original/` — Original vulnerable source files
- `report/repository_report.md` — Full security report
- `report/scan_data.json` — Raw scan data

*Generated by AegisFlow v2.0*
"""
        zf.writestr("README.md", readme)

    return buffer.getvalue()


def get_file_extension(language: str) -> str:
    return LANGUAGE_EXTENSIONS.get(language.lower(), ".txt")
