"""
AegisFlow - PR Service
Handles automatically pushing fixed code to GitHub and raising Pull Requests.
"""
import os
import uuid
from github import Github
from github.GithubException import GithubException

def create_remediation_pr(github_token: str, repo_name: str, file_path: str, fixed_code: str, vulnerability_details: str):
    """
    Automatically creates a new branch, commits the fixed code, and raises a Pull Request.
    
    Args:
        github_token: GitHub Personal Access Token
        repo_name: Full repository name (e.g. 'BiBiShA21/aegisflow')
        file_path: Path to the file being fixed (e.g. 'backend/app.py')
        fixed_code: The safe code generated by the AI
        vulnerability_details: Description of what was fixed
    
    Returns:
        The URL of the created Pull Request.
    """
    if not github_token:
        # Fallback to env variable if token not provided directly
        github_token = os.getenv("GITHUB_PAT")
        
    if not github_token:
        print("[PR SERVICE] Warning: No GITHUB_PAT provided. Cannot create PR.")
        return None

    try:
        g = Github(github_token)
        repo = g.get_repo(repo_name)
        
        # 1. Get the default branch and its latest commit
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        
        # 2. Create a new branch for the fix
        short_id = str(uuid.uuid4())[:8]
        new_branch_name = f"aegisflow-fix-{short_id}"
        repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=ref.object.sha)
        
        print(f"[PR SERVICE] Created new branch: {new_branch_name}")
        
        # 3. Get the existing file to get its blob SHA
        file_content = repo.get_contents(file_path, ref=default_branch)
        
        # 4. Commit the fixed code to the new branch
        commit_message = f"🛡️ AegisFlow: Automated Security Fix for {file_path}"
        repo.update_file(
            path=file_content.path,
            message=commit_message,
            content=fixed_code,
            sha=file_content.sha,
            branch=new_branch_name
        )
        print(f"[PR SERVICE] Committed fixed code to {file_path}")
        
        # 5. Raise the Pull Request
        pr_title = f"🛡️ AegisFlow Security Remediation: {file_path}"
        pr_body = f"""
## AegisFlow Automated Security Fix

This is an autonomous security fix generated by the **AegisFlow DevSecOps Pipeline**.

**File Fixed:** `{file_path}`

### Details of the Vulnerability:
{vulnerability_details}

---
*Please review the changes carefully before merging. This fix was verified in a sandbox but requires human approval.*
"""
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            base=default_branch,
            head=new_branch_name
        )
        
        print(f"[PR SERVICE] Successfully created Pull Request: {pr.html_url}")
        return pr.html_url

    except GithubException as e:
        print(f"[PR SERVICE ERROR] GitHub API Error: {e.data}")
        raise e
    except Exception as e:
        print(f"[PR SERVICE ERROR] Failed to create PR: {str(e)}")
        raise e
